### ISSUE TITLE
errors in count regression page

### ISSUE THREAD

**Issue by EvoArt** [storopoli/Bayesian-Julia#20]
There are a few undefvar errors in the poisson/negbin2 with turing page. On the actual website that is.

**Comment by storopoli** [comment]
Thanks for noticing. Something with GHA I'll try to rerun the job.

**Comment by EvoArt** [comment]
No worries. Thanks for the site! Couldn't get my head around negative binomial regression till now. Without the reparametization it just made no intuitive sense.

**Comment by storopoli** [comment]
Wow that was hard. Something activated the installation of Parsers.jl version 2.0 in the parent CI job and then crashed CSV.jl precompilation in the child process while building the content. CSV.jl v0.8.5 only works with Parsers.jl v1.x.

You may now enjoy and read the content. Thanks for letting me know that the content was broken.

Fixed by cd59d03 and cac0f37.

Thanks for @quinnj in spotting the mistake:

> JSON.jl is pulling in Parsers.jl for Franklin.jl, and JSON.jl recently released a new version compatible w/ either Parsers.jl 1.0 or 2.0, so unless it’s pinned otherwise, it would default to 2.0.
