### ISSUE TITLE
Chapter 4: possible error in description of Turing's warmup defaults

### ISSUE THREAD

**Issue by adder** [storopoli/Bayesian-Julia#30]
Hey,

Thanks for the great tutorial! 
However I think I have spotted an error in chapter 4.
Here you say :

```
Please note that, as default, Turing samplers will discard the first half of iterations as warmup. 
So the sampler will output 1,000 samples (floor(2_000 / 2)):
chain = sample(model, NUTS(), 2_000);
```
https://github.com/storopoli/Bayesian-Julia/blob/master/_literate/4_Turing.jl#L162

However in the figure below that, `plot(chain)`, you can see that the samples start from sample 1000 and go to sample 3000.
https://storopoli.io/Bayesian-Julia/assets/pages/4_Turing/code/output/chain.svg

So to me it seems that if you specify 2000 samples in the `sample()` function, Turing will add and extra 1000 warmup sample that get discarded afterwards. 
You think this is correct?

I tried to look it up in the Turing documentation, but it not immediately clear to me where I can find this information in their documentation. 
I am new to Julia, coming from R, and finding the right documentation in Julia land is still a challenge to me sometimes.

Best

**Comment by storopoli** [comment]
You are definitely right. The documentation can be found [here](https://github.com/TuringLang/Turing.jl/blob/master/src/inference/hmc.jl#L336-L354) or by typing:

```julia
using Turing
help(sample)
```

Since I do not specified any parameters inside the `NUTS()` constructor it will inherit the default which are:

```julia
NUTS(1_000, 0.65)
```

that uses `1_000` adaption steps for the dual-averaging Nesterov algorithm, and target accept ratio `0.65`.

So the correct would be:

> Please note that, as default, Turing samplers will discard the first thousand (1,000) iterations as warmup. 
So the sampler will output 2,000 samples:
`chain = sample(model, NUTS(), 2_000);`

Do you want to make a PR to fix this? We would probably need to update elsewhere. I would advise to search for all "sample" strings in the `_literate/` folder and check the occurrences' surrounding text so that we are sure to cover all mentions.

**Comment by adder** [comment]
Thanks a lot for the clarification and it seems you did the PR already yourself :+1:

**Comment by storopoli** [comment]
Yeah, I was with this fresh in my mind so I decided to just do it. If you want to improve, any PR or issue would be most welcome.
